/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MainApp;

import Account.SQLConnection;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author kyanh
 */
public class SuaThongTin extends javax.swing.JFrame {

    private String User;

    /**
     * Creates new form SuaThongTin
     */
    public SuaThongTin(String user) {
        initComponents();
        setVisible(true);
        this.User = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtfTruong = new javax.swing.JTextField();
        jcbNu = new javax.swing.JCheckBox();
        jcbNam = new javax.swing.JCheckBox();
        jtfHoTen = new javax.swing.JTextField();
        jtfSdt = new javax.swing.JTextField();
        jtfEmail = new javax.swing.JTextField();
        btnSuaTT = new javax.swing.JButton();
        jlbLoi = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(58, 81, 153));

        jPanel2.setBackground(new java.awt.Color(254, 244, 230));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 458));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Tên trường:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Họ và tên:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Ngày sinh:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Email:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Giới tính: ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Số điện thoại: ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jtfTruong.setBorder(null);
        jPanel2.add(jtfTruong, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 260, 30));

        jcbNu.setBackground(new java.awt.Color(254, 244, 230));
        jcbNu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jcbNu.setText("Nữ");
        jcbNu.setIconTextGap(8);
        jPanel2.add(jcbNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 60, 30));

        jcbNam.setBackground(new java.awt.Color(254, 244, 230));
        jcbNam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jcbNam.setText("Nam");
        jcbNam.setIconTextGap(8);
        jPanel2.add(jcbNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 60, 30));

        jtfHoTen.setBorder(null);
        jPanel2.add(jtfHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 260, 30));

        jtfSdt.setBorder(null);
        jPanel2.add(jtfSdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 260, 30));

        jtfEmail.setBorder(null);
        jPanel2.add(jtfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 260, 30));

        btnSuaTT.setBackground(new java.awt.Color(58, 81, 153));
        btnSuaTT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSuaTT.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaTT.setText("Chỉnh sửa");
        btnSuaTT.setBorder(null);
        btnSuaTT.setBorderPainted(false);
        btnSuaTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaTTActionPerformed(evt);
            }
        });
        jPanel2.add(btnSuaTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 170, 40));

        jlbLoi.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(jlbLoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 260, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CHỈNH SỬA TÀI KHOẢN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaTTActionPerformed
        String HoTen = jtfHoTen.getText();
        //       String NgSinh = jtfNgSinh.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-mm-yyyy");
//        String NgSinh = sdf.format(jDateChooser.getDate());
        String Sdt = jtfSdt.getText();
        String Email = jtfEmail.getText();
        String Truong = jtfTruong.getText();
        int GTinh;
        if (HoTen.isEmpty() || Sdt.isEmpty() ||Email.isEmpty() || Truong.isEmpty()||
            (jcbNam.isSelected() && jcbNu.isSelected()) || (!jcbNam.isSelected() && !jcbNu.isSelected())) {
            jlbLoi.setText("Vui lòng nhập thông tin đầy đủ và chính xác");
        }
        else {
            try{
                if (jcbNam.isSelected()) GTinh = 1;
                else GTinh = 0;
                Connection conn = SQLConnection.getSQLConnection();
                String Sql = "update NGUOIDUNG\n" +
                "set TENND = ?, GTINH = ?, DTHOAI = ?, Email = ?, TRUONG = ?\n" +
                "where MAND = ?" ;
                PreparedStatement ps = conn.prepareStatement(Sql);
                ps.setString(1, HoTen);
//                ps.setString(2,NgSinh);
                ps.setInt(2, GTinh);
                ps.setString(3, Sdt);
                ps.setString(4, Email);
                ps.setString(5, Truong);
                ps.setString(6, this.User);
                int rs = ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Chỉnh sửa thành công!");
                this.dispose();
            }
            catch (Exception ex){
                JOptionPane.showMessageDialog(null, ex);
                //jlbLoi.setText("Vui lÃ²ng nháº­p thÃ´ng tin Ä‘Ãºng!");
            }

        }
    }//GEN-LAST:event_btnSuaTTActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaTT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox jcbNam;
    private javax.swing.JCheckBox jcbNu;
    private javax.swing.JLabel jlbLoi;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfHoTen;
    private javax.swing.JTextField jtfSdt;
    private javax.swing.JTextField jtfTruong;
    // End of variables declaration//GEN-END:variables
}
